### ISSUE TITLE
[MakefileVC] Make DiabloUI compile correctly

### ISSUE THREAD

**Issue by seritools** [diasurgical/devil-nightly#149]
https://github.com/diasurgical/devilution/commit/a3800a3d4cf30195650b8dda96d764201144d5e6

This currently breaks the VC makefiles, thus breaking riivaaja as well (reverted it for now)

**Comment by galaxyhaxz** [comment]
Fixed now, the UI code was updated: https://github.com/diasurgical/devilution/blob/master/MakefileVC

**Comment by seritools** [comment]
Fixed with 9cf3a62ca809b692d8a02c36a5e1ead7bd04b7f6
