### ISSUE TITLE
Find the cause for minor compilation differences

### ISSUE THREAD

**Issue by seritools** [diasurgical/devil-nightly#15]
Tracking issue for minor compilation differences that don't seem to be caused by the function code itself.

- [x] Adress calculation weirdness

For some reason instructions are often reordered in a way that an address is calculated multiple times:

Diablo:

```asm
lea edx, [eax+0x68AB88]
cmp dword ptr [edx], 0xFFFFFFFF
```

Devilution:

```asm
cmp dword ptr [eax+0x688F68], 0xFFFFFFFF
lea edx, [eax+0x688F68]
```

This causes the function size to grow.

I've seen this happen multiple times, for example in `CheckInvCut` (#12), but lots of times it's calculated correctly.

- [x] `xor eax, eax; inc eax` (Diablo) vs `push 1; pop eax` (devilution)

It just doesn't make any sense. Same 3 bytes long, same registers used, but devilution code often generates code that's loading a constant `1` via stack...

**Comment by AJenbo** [comment]
Glad to see it's not just me facing this 😊

**Comment by seritools** [comment]
Alright, I was browsing the net for VS/VC 6 beta versions and stumbled upon something called "Visual C++ 6.0 Processor Pack". @nomdenom helped me find the downloads for that.
There are two versions, one for SP4 and one for SP5. Installed both in their own respective VM snapshots, and....

![image](https://user-images.githubusercontent.com/5844066/44747032-59d6b280-ab0c-11e8-8926-2cf9d1b35e6c.png)

DONE! 🎉 

Both SP4+Pack and SP5+Pack generate proper code for both of the issues mentioned above. This now limits the used tools to just 2 different versions, and probably means that the optimization flags are pretty much correct for now as well!


  | SP4 | SP4+PP | SP5 | SP5+PP
-- | -- | -- | -- | --
C1.DLL | 12.0.8867.0 | same | 12.0.8867.0 | same
C2.DLL | 12.0.8799.0 | 13.0.8943.0 | 12.0.8966.0 | 13.0.9044.0
C1XX.DLL | 12.0.8867.0 | same | 12.0.8964.0 | same

**Comment by seritools** [comment]
![image](https://user-images.githubusercontent.com/5844066/44749984-77a81580-ab14-11e8-89a0-b912466ecec6.png)

`CalcPlrItemVals` is now binary exact, after the new compiler version helped me find a tiny bug I introduced :D (https://github.com/diasurgical/devil-nightly/commit/22718733d0a706953baddd0283b9a61a1fe3b852)

So basically every small difference is fixed now. Instruction ordering, codegen, address calculation.

**Comment by mewmew** [comment]
> So basically every small difference is fixed now. Instruction ordering, codegen, address calculation.

Oh, wow! This is soooo great!! Really good job @seritools, @AJenbo and @nomdenom.
