### ISSUE TITLE
Merge into main repo

### ISSUE THREAD

**Issue by galaxyhaxz** [diasurgical/devil-nightly#150]
Now that all the bugs are fixed and the UI garbage is out of the way, we can keep development in one repo. Anything that's bin exact, feel free to send it over.

**Comment by mewmew** [comment]
Wonderful to see Devilution having reached the point of fixing the major known bugs :) Let the merge begin!

**Comment by seritools** [comment]
@galaxyhaxz just do a force-push of devil-nightly over at devilution, everything is merged now :P

**Comment by seritools** [comment]
so much for that...

![image](https://user-images.githubusercontent.com/5844066/45706037-81ed8a80-bb7b-11e8-932e-a2dcd6bc9e23.png)

Broken history, commit authors, comments etc., nice.

**Comment by mewmew** [comment]
BOOM!
