### ISSUE TITLE
Update the MakefileVC to allow building with PDB output

### ISSUE THREAD

**Issue by seritools** [diasurgical/devil-nightly#16]
Allow switching between PDB (has to be linked with VC6 link.exe) and regular build (VC5 link.exe 5.1) via environment variable

**Comment by AJenbo** [comment]
This can now be done with MAKE_BUILD=pdb as of https://github.com/diasurgical/devil-nightly/commit/71f890a29bf31b7dceb211a402ee7e0d7ebdade1

**Comment by seritools** [comment]
Closed by #17
