### ISSUE TITLE
Go back and recheck all old cleanups

### ISSUE THREAD

**Issue by seritools** [diasurgical/devil-nightly#18]
Now that the compiler version and flags seem to be correct, I'll have to go back through my older cleanups and check/fix them against the new tools.

- [x] InitMonsterTRN
- [x] InitLevelMonsters
- [x] AddMonsterType
- [x] GetLevelMTypes
- [x] InitMonsterGFX
- [x] InitMonster
- [x] MonstPlace
- [x] PlaceMonster
- [x] PlaceUniqueMonst
- [x] PlaceGroup
- [x] GetManaAmount
- [x] UseMana
- [x] CheckSpell
- [x] CastSpell
- [x] DoResurrect
- [x] PlacePlayer
- [x] DoHealOther

(just a tracking issue for me, will update/add stuff here)

**Comment by seritools** [comment]
Done, all old commits cleaned up, so that everything (where possible) is binary exact! 🎉 
All remaining (very minimal) differences are added as individual issues.

**Comment by AJenbo** [comment]
nice work :)

**Comment by mewmew** [comment]
Really great! Who would have thought that getting a binary identical version of Diablo 1 was actually obtainable.
