### ISSUE TITLE
InitMonsterGFX: Same eax register is reused instead of ecx

### ISSUE THREAD

**Issue by seritools** [diasurgical/devil-nightly#20]
This happens when calculating

```cpp
	Monsters[monst].MData = &monsterdata[mtype];
	Monsters[monst].flags_1 = monsterdata[mtype].flags;
	Monsters[monst].flags_2 = (monsterdata[mtype].flags - 64) >> 1;
	Monsters[monst].mMinHP = monsterdata[mtype].mMinHP;
	Monsters[monst].mMaxHP = monsterdata[mtype].mMaxHP;
	Monsters[monst].has_special = monsterdata[mtype].has_special;
	Monsters[monst].mAFNum = monsterdata[mtype].mAFNum;
```

Tried a few things (local variable, accessing `flags_1`), but nope:

![image](https://user-images.githubusercontent.com/5844066/44757724-d7141e80-ab30-11e8-87da-e358971cf267.png)

**Comment by mewmew** [comment]
It is possible that the caller of this function uses ecx, or that a callee spills it, or some other combination, which may change the register selection. Just a theory.

**Comment by AJenbo** [comment]
So find the caller and clean it next I guess 😊

**Comment by seritools** [comment]
Nah, it's in the middle of the function and both eax and ecx have been used before that part (and the function is `__fastcall`, so ecx is the first parameter ;) )
