### ISSUE TITLE
Data File Error on old save

### ISSUE THREAD

**Issue by ChaosMarc** [diasurgical/devil-nightly#31]
I have a savegame ([single_0.zip](https://github.com/diasurgical/devil-nightly/files/2347999/single_0.zip)) which I created with devilution 0.3 and played it since (always with a current build of the devilution repo), which cannot be loaded with a current devil-nighlty build, but with a current devilution build or the original Diablo executable.

When trying to load the game I receive the following two error messages:
![error1](https://user-images.githubusercontent.com/1343751/45022215-ee24a600-b033-11e8-8eaf-1dd0eb08d54f.png)
![error2](https://user-images.githubusercontent.com/1343751/45022221-f11f9680-b033-11e8-897f-6911d4d982d8.png)

creating a new game or loading other saves is no problem. I have the CD mounted in a virtual drive

The missing monster "Bilefroth the Pit Master" should spawn on level 6 which is exactly where my character is located

**Comment by mewmew** [comment]
> The missing monster "Bilefroth the Pit Master" should spawn on level 6 which is exactly where my character is located

I'll try to resolve this one :)

**Comment by mewmew** [comment]
@ChaosMarc would you mind trying the fix in #32? If it works we can merge it and close the issue :)

**Comment by ChaosMarc** [comment]
It's fixed. Thanks for the quick help :)
