### ISSUE TITLE
belt items aren't consumed optically

### ISSUE THREAD

**Issue by ChaosMarc** [diasurgical/devil-nightly#38]
With the latest nightly, after drinking a potion via 1-8 it will still be displayed until hovered with the mouse or the game is saved

**Comment by seritools** [comment]
git bisect to the rescue, tracked it down to 07b5dc3939564abe687924c69400ca56ee05c6ed, will look into it :)

**Comment by ChaosMarc** [comment]
yeah :) that fixed it. thank you @seritools
