### ISSUE TITLE
TravisCI: Compile devilution with VC++/wine?

### ISSUE THREAD

**Issue by seritools** [diasurgical/devil-nightly#4]
It would be nice if we'd compile devilution as part of CI via VC++ 5/6 and wine to make sure all PRs are compatible with the original build structure.

I don't really have any experience with that, so info or help on that would be greatly appreciated!

**Comment by AJenbo** [comment]
I actually might be able to do this, I have set up my share of CI setups at this point, and it goes well with me trying to get it all working on my Linux box atm 😊

**Comment by seritools** [comment]
Would be very cool! :)

**Comment by AJenbo** [comment]
It compiles with gcc (Linux), llvm (Mac) and Visual studio 2017 (Windows). The problem is that they all produce very different code to the Visual Studio 6 compiler so we need it to track the projects progress. So this is about making sure that the code stays compatible with that specific compiler.

**Comment by seritools** [comment]
@ttdonovan Devil-nightly already runs with travis, using the devilution config. That config however currently only does cross-compiled builds with modern compilers. In order to make sure every change is compatible with the original tooling we thought of adding a build solution with the old VC toolset.

In the future, this could also allow us to get additional statistics and build artifacts that are comparable to the original binary. As @AJenbo said, modern compilers compile and optimize completely differently, so proper comparisons are pretty much impossible.
